---
sudo: true

addons:
  apt:
    packages:
      - python
      - realpath

env:
  global:
     CONTAINER_REPO="gluster/gluster-mixins"
language: go

go:
  # Kubernetes minimum_go_version can be found in this file:
  # https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh
  - stable

install:
  - go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
  - go get github.com/prometheus/prometheus/cmd/promtool
  - git clone https://github.com/google/jsonnet ${TRAVIS_HOME}/jsonnet
  - make -C ${TRAVIS_HOME}/jsonnet CC=clang CXX=clang++
  - cp ${TRAVIS_HOME}/jsonnet/jsonnet ${TRAVIS_HOME}/gopath/bin
  - cp ${TRAVIS_HOME}/jsonnet/jsonnetfmt ${TRAVIS_HOME}/gopath/bin
  - jb install
script:
  - set -o pipefail &&
    find . -name 'vendor' -prune -o -name '*.libsonnet' -print -o -name '*.jsonnet' -print | 
    while read f; do 
        jsonnetfmt -n 2 --max-blank-lines 2 --string-style s --comment-style s "$f" | diff -u "$f" -; 
    done

  - make all
  - ./build.sh "${CONTAINER_REPO}"

deploy:
  # Master branch will push the container to :latest
  - provider: script
    on:  # yamllint disable-line rule:truthy
      branch: master
    script: .travis/push_container.sh ${CONTAINER_REPO} verbatim latest
  # Tags of the form v + SEMVER (e.g., v1.2.3) will push to the
  # corresponding container version number (e.g., :1.2.3).
  - provider: script
    on:  # yamllint disable-line rule:truthy
      tags: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+
    script: .travis/push_container.sh ${CONTAINER_REPO} version "$TRAVIS_TAG"
